// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKxKs7hfAaYZ0FPK8HBWi2Qz2976Qw5A4',
    appId: '1:694385076529:web:b362e377ad998c29ea6810',
    messagingSenderId: '694385076529',
    projectId: 'pa-mobile-eb5e7',
    authDomain: 'pa-mobile-eb5e7.firebaseapp.com',
    storageBucket: 'pa-mobile-eb5e7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEO_LnRKgzJs8PekWFUM7dg4HGaGpfNms',
    appId: '1:694385076529:android:7db4255d18ae2addea6810',
    messagingSenderId: '694385076529',
    projectId: 'pa-mobile-eb5e7',
    storageBucket: 'pa-mobile-eb5e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM3fsWkh1g0_qfCtJjWfN3lkVvuDZQqD0',
    appId: '1:694385076529:ios:5a0bc8d96722f136ea6810',
    messagingSenderId: '694385076529',
    projectId: 'pa-mobile-eb5e7',
    storageBucket: 'pa-mobile-eb5e7.firebasestorage.app',
    iosBundleId: 'com.example.coffee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM3fsWkh1g0_qfCtJjWfN3lkVvuDZQqD0',
    appId: '1:694385076529:ios:5a0bc8d96722f136ea6810',
    messagingSenderId: '694385076529',
    projectId: 'pa-mobile-eb5e7',
    storageBucket: 'pa-mobile-eb5e7.firebasestorage.app',
    iosBundleId: 'com.example.coffee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKxKs7hfAaYZ0FPK8HBWi2Qz2976Qw5A4',
    appId: '1:694385076529:web:f6521015a73cfdc7ea6810',
    messagingSenderId: '694385076529',
    projectId: 'pa-mobile-eb5e7',
    authDomain: 'pa-mobile-eb5e7.firebaseapp.com',
    storageBucket: 'pa-mobile-eb5e7.firebasestorage.app',
  );
}
